-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME FROM ANIMAL_OUTS A LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID WHERE B.ANIMAL_ID IS NULL ORDER BY A.ANIMAL_ID;

# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I 
#     ON (O.ANIMAL_ID = I.ANIMAL_ID)
# WHERE I.ANIMAL_ID IS NULL
# ORDER BY O.ANIMAL_ID